version: "3"
services:
  web:
    image: unfrgivn/nginx-php-fpm
    restart: unless-stopped
    ports:
      - "${LOCAL_PORT_WEB}:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/extras/rewrites.conf:/etc/nginx/extras-enabled/rewrites.conf
      - ./nginx/extras/security.conf:/etc/nginx/extras-enabled/security.conf
      - ./nginx/errors/error-handler.php:/var/www/errors/error-handler.php
    environment:
      WEBROOT: /var/www/html/web
      ENABLE_XDEBUG: ${ENABLE_XDEBUG}
      PHP_ERRORS_STDERR: ${PHP_ERRORS_STDERR}
      NGINX_ERRORS: ${NGINX_ERRORS}
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PREFIX: ${DB_PREFIX}
      WP_ENV: ${WP_ENV}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_HOME}/wp
      WP_FRAMEWORK: ${WP_FRAMEWORK}
      WP_DEBUG: ${WP_DEBUG}
      WP_DEBUG_NO_WARNINGS: ${WP_DEBUG_NO_WARNINGS}
      AUTH_KEY: ${AUTH_KEY}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      NONCE_KEY: ${NONCE_KEY}
      AUTH_SALT: ${AUTH_SALT}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_SALT: ${NONCE_SALT}

  mysql:
    image: mysql:8.0.20
    restart: unless-stopped
    ports:
      - "${LOCAL_PORT_DB}:3306"
    volumes:
      - mysql:/var/lib/mysql
      # If you need to override the default MySQL config you can map it here
      # - ./mysql/my.cnf:/etc/mysql/conf.d/zz_my.cnf:ro #zz_ so cnf file is loaded last
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: America/New_York
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql:
    driver: "local"
